[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Api-Key, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Methods = "*"